node {
    currentBuild.result = "SUCCESS"
    properties([
      gitLabConnection('roger-gitlab'),
      parameters([string(defaultValue: 'v1', description: '', name: 'TAG_VERSION', trim: false)])
    ])

    try {
      stage 'mock CD with success status'
          sh """
              echo "TAG_VERSION: ${TAG_VERSION}"
              echo 'Success CD job build! (This is from Rogers Mac)'
          """

      stage 'Notify Slack CD successful'
        def attachments = [
          [
              text: 'Success CD job build! (This is from Rogers Mac)',
              color: '#5afa60'
          ]
        ]
      slackSend(attachments: attachments)

    } catch (err) {
      def attachments = [
        [
            text: 'Mock CD job Failed! This is from Rogers Mac!',
            color: 'rgb(250, 40, 71)'
        ]
      ]

      slackSend(attachments: attachments)

      throw err

    } finally {

    }
}
